In [1]:
# importing torch library
import torch

In [18]:
x = torch.ones(2, 2, dtype = torch.int)

In [19]:
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [20]:
print(x.dtype)

torch.int32


In [22]:
print(x.size())

torch.Size([2, 2])


In [23]:
x = torch.tensor([2, 5, 1])

In [24]:
print(x)

tensor([2, 5, 1])


In [25]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [26]:
print(x)
print(y)

tensor([[0.5510, 0.7971],
        [0.0708, 0.0997]])
tensor([[0.4854, 0.7058],
        [0.2767, 0.4376]])


In [27]:
x + y

tensor([[1.0365, 1.5029],
        [0.3475, 0.5372]])

In [29]:
torch.add(x, y)

tensor([[1.0365, 1.5029],
        [0.3475, 0.5372]])

In [32]:
# autograd - calculates gradient autmatically
x = torch.randn(3, requires_grad = True)

In [33]:
print(x)

tensor([-1.2388,  0.7481,  0.1928], requires_grad=True)


In [34]:
y = x + 2

In [35]:
print(y)

tensor([0.7612, 2.7481, 2.1928], grad_fn=<AddBackward0>)


In [39]:
z = y*y*2
z = z.mean()
print(z)

tensor(8.6267, grad_fn=<MeanBackward0>)


In [40]:
z.backward()


In [41]:
print(x.grad)

tensor([1.0149, 3.6642, 2.9237])
